#!/usr/bin/env node

/**
 * Prints the CHANGELOG section for a version, so the release workflow can use
 * the notes the project already wrote instead of an autogenerated commit list.
 *
 * Usage: node scripts/release-notes.js <version>
 * Exits 1 when the changelog has no section for that version, which lets the
 * workflow fall back to GitHub's generated notes.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { extractNotes } from './lib/changelog.js';

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const version = process.argv[2];

if (!version) {
  console.error('Usage: node scripts/release-notes.js <version>');
  process.exit(2);
}

const notes = extractNotes(fs.readFileSync(path.join(ROOT_DIR, 'CHANGELOG.md'), 'utf-8'), version);

if (!notes) {
  console.error(`No CHANGELOG.md section found for ${version}.`);
  process.exit(1);
}

process.stdout.write(notes + '\n');
