import fs from 'node:fs';
import path from 'node:path';
import { logHeading, logInfo, logSuccess } from '../ui.js';
import { ensureOutputDir } from '../utils/output.js';

/**
 * Splits a task into a checklist for five agent personas, following the SPARC
 * roles from ruvnet/ruflo, and saves it to .smileu/tasks/. It writes a plan; it
 * does not run any agents.
 */
export function runSwarmDecomposition(task, targetDir = process.cwd()) {
  logHeading(`Task plan: ${task}`);
  logInfo('Hand each section to the matching agent persona.');

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const plan = {
    task,
    timestamp: new Date().toISOString(),
    methodology: 'SPARC (Specification, Pseudocode, Architecture, Refinement, Completion)',
    swarm: [
      {
        role: 'Lead Architect (@architect)',
        mission: 'Define system interfaces, schema boundaries, and the dependency graph.',
        actions: [
          'Read .smileu/graph/graph.json (create it with the graph command, or /smileu graph) to trace the blast radius.',
          `Draft data contracts and interface types for "${task}".`,
          'Record non-obvious design choices in docs/adr/ when needed.'
        ]
      },
      {
        role: 'Feature Engineer (@engineer)',
        mission: 'Implement the logic, API handlers, and pure functions.',
        actions: [
          'Write modular, strictly typed code that satisfies the architect specification.',
          'Implement pure data transformations and explicit error paths.',
          'Leave no unhandled promise rejections or silent failures.'
        ]
      },
      {
        role: 'Design & Motion Specialist (@craft)',
        mission: 'Apply the frontend design standards and motion rules.',
        actions: [
          'Keep typography on a consistent scale.',
          'Use ease-out (200ms) for entering elements and ease-in (150ms) for exiting elements.',
          'Avoid nested cards, pure #000000 black, and default purple gradients.'
        ]
      },
      {
        role: 'Security Guardian (@guardian)',
        mission: 'Apply OWASP Top 10 defenses at every boundary.',
        actions: [
          'Validate all external input with a schema validator (Zod, Valibot).',
          'Keep API keys, JWT secrets, and tokens out of source code.',
          'Prevent SQL injection, command string concatenation, and XSS.'
        ]
      },
      {
        role: 'Humanizer Editor (@editor)',
        mission: 'Remove stock AI phrasing from docs, commit messages, and PR descriptions.',
        actions: [
          'Read the commit message, PR description, and docs for stock AI phrases.',
          'Cut inflated words and lists padded out to three items.',
          'Keep messages short and factual.'
        ]
      }
    ]
  };

  plan.swarm.forEach((agent, i) => {
    console.log(`\n${i + 1}. ${agent.role}`);
    console.log(`   Mission: ${agent.mission}`);
    agent.actions.forEach((act) => console.log(`   - ${act}`));
  });
  console.log('');

  const tasksDir = ensureOutputDir(targetDir, 'tasks');
  const taskFilePath = path.join(tasksDir, `task-${timestamp}.md`);
  const markdownContent = `# Task Plan: ${task}

**Generated:** ${plan.timestamp}
**Methodology:** ${plan.methodology}

---

${plan.swarm
  .map(
    (a, i) => `## ${i + 1}. ${a.role}
**Mission:** ${a.mission}

**Checklist:**
${a.actions.map((act) => `- [ ] ${act}`).join('\n')}
`
  )
  .join('\n')}

---
*Generated by smileu swarm*
`;

  fs.writeFileSync(taskFilePath, markdownContent, 'utf-8');
  logSuccess(`Task plan saved to ${path.relative(targetDir, taskFilePath).replace(/\\/g, '/')}`);
  return plan;
}
